name: build

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        shell: cmd
        run: build-all.bat
  linux:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: bash build-all.sh
